#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-common-artifact-filters
Version  : 1.4
Release  : 2
URL      : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.pom
Source2  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.jar
Source3  : https://repo1.maven.org/maven2/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-common-artifact-filters-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-common-artifact-filters package.
Group: Data

%description data
data components for the mvn-maven-common-artifact-filters package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.jar
/usr/share/java/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/3.0.1/maven-common-artifact-filters-3.0.1.pom
